### ISSUE TITLE
Verificar como os modelos entrarão no fortran 

### ISSUE THREAD

**Issue by Caicau** [GISIS-UFF/RTM_python-fortran#36]
trecho para ser alterado: linhas 100 a 110
 if (regTTM == 0) then
  
     if (**caminho_modelo  == "../modelos_utilizados/marmousi_vp_383x141.bin"**) then
        CALL Seismogram(Nt,Nx,shot,"Marmousi","../sismograma/",Seism)
     end if
  
     if (**caminho_modelo == '../modelos_utilizados/velocitymodel_Hmgns_wtrly.bin'**) then   
        CALL Seismogram(Nt,Nx,shot,"Homogeneo","../sismograma_modelo_camada_de_agua/",Seism)
     end if
  end if

**Comment by fetim** [comment]
Resolve isso logo! @Caicau

**Comment by fetim** [comment]
@Caicau , Posso fechar essa?
