### ISSUE TITLE
Implementar a Migração 

### ISSUE THREAD

**Issue by fetim** [GISIS-UFF/RTM_python-fortran#49]
@Caicau, Essa é a issue da migração. Se precisar de alguma ajuda coloque aqui as dúvidas

**Comment by Caicau** [comment]
@fetim Resultados obtidos nos testes feitos:

2 tiros:

![marmousi_multiprocessing_2_tiros](https://user-images.githubusercontent.com/34284723/42765358-3bd1913c-88ee-11e8-996e-ffc36939c906.png)

8 tiros

![imagem_marmousi_8_shots](https://user-images.githubusercontent.com/34284723/42774688-b5dd30f2-8908-11e8-82f4-b505c3acaf43.png)

Acredito que o artefato na matriz de tempo de trânsito não está prejudicando a imagem. O que você acha?

**Comment by fetim** [comment]
@Caicau também acho que está funcionando bem

**Comment by Caicau** [comment]
@fetim Ok! Eu recebi um email do github falando daquele problema de conexão que ocorreu. Eles falaram que pode haver alguns problemas com meu último push. Vou verificar e, caso esteja tudo ok, crio um pull request

**Comment by Caicau** [comment]
@fetim Acredito que podemos fechar essa issue, não? Se eu não me engano já fizemos o merge da migração para o repositório principal.
