### ISSUE TITLE
Implementar a remoção da onda direta

### ISSUE THREAD

**Issue by fetim** [GISIS-UFF/RTM_python-fortran#51]
- [x] implementação em script diferente

- [x] Modelagem com o modelo que somente tem a camada de água e registrar os sismogramas

- [x] Ler os sismogramas observados (gerados na primeira modelagam)

- [x] Realizar diferençca entre sismograma observado e sismograma com somente a camada de agua

- [x] Registrar sismograma sem onda direta

**Comment by fetim** [comment]
Alteração no modulo fortran:
subrotina nucleomodelagem

Remover ID_modelo e colocar caminho_sismograma e nome_prin

 `SUBROUTINE nucleomodelagem(Nz,Nx,Nt,dh,dt,NpCA,shot,shotshow,NSx,NSz,fonte,Nfonte,Nsnap,regTTM,caminho_modelo,zr,caminho_sismograma,nome_prin)`


`  if (regTTM == 0) then
     CALL Seismogram(Nt,Nx,shot,trim(nome_prin),trim(caminho_sismograma),Seism)
  else if (regTTM == 1) then
     CALL writematrix(Nz,Nx,shot,TTM,trim(nome_prin),"../matriz_tempo_transito/")
  end if
`

**Comment by fetim** [comment]
Ainda no módulo fortran:
subrotina removeondadireta

Passar as várias aqui também

**Comment by Caicau** [comment]
@fetim Então, consegui realizar a remoção. Mas não consegui fazer a modelagem do modelo de camada e a remoção juntas. Primeiro tive que criar os sismogramas e depois fiz a remoção. Vou verificar qauis podem ser os erros e atualizo aqui.

![sismograma_onda_direta](https://user-images.githubusercontent.com/34284723/42467653-dd952710-8388-11e8-8778-489c69ca34a2.jpeg)
![onda_direta](https://user-images.githubusercontent.com/34284723/42467670-e8e7df90-8388-11e8-8d95-89367b108db8.jpeg)
![sismograma_sem_onda_direta](https://user-images.githubusercontent.com/34284723/42467680-ec466de6-8388-11e8-83e2-a95fc99453c4.jpeg)

**Comment by fetim** [comment]
Isso mesmo!!!

**Comment by fetim** [comment]
:shipit: Funcionando no mesmo script. @Caicau fiz um pull request para seu repositório. Não esquece de fazer o merge.
