### ISSUE TITLE
Colocar descrição em todas as funções e subrotinas

### ISSUE THREAD

**Issue by fetim** [GISIS-UFF/RTM_python-fortran#52]
Use no ínicio do script em python

`# -*- coding: utf-8 -*-`

Fiz um teste no python 2 e funcionou a acentuação.

- [ ] Concluido ?

**Comment by fetim** [comment]
@Caicau posso fechar essa issue?

**Comment by fetim** [comment]
Ainda não

**Comment by Caicau** [comment]
Vou testar esse código amanhã no gisis e, se funcionar, a gente pode fechar :wink:

**Comment by fetim** [comment]
@Caicau, comece pelo auxfunctionsmodule.py

**Comment by Caicau** [comment]
@fetim Começar o que? As descrições??

**Comment by fetim** [comment]
isso!

**Comment by Caicau** [comment]
@fetim Eu já coloquei as descrições nas funções. Você pode verificar e, se tudo estiver correto, fechar essa issue?

**Comment by fetim** [comment]
@Caicau  corrigir essa linha:
https://github.com/Caicau/RTM_python-fortran/blob/00dcf48ac5a3dddf5e340bf8af78655d7bce171b/src/auxfunctionsmodule.py#L81

**Comment by Caicau** [comment]
@fetim  Corrigida! Assim que o script de migração estiver funcionando envio tudo junto.
