### ISSUE TITLE
Problema ao declarar as variáveis "nome_prin" e "caminho_sismograma"

### ISSUE THREAD

**Issue by Caicau** [GISIS-UFF/RTM_python-fortran#53]
@fetim Tive problemas ao tentar compilar a F2Py. Ela não indicou nenhum problema específico, mas acredito que esteja relacionado com a declaração das variáveis strings. Você pode ver o que eu modifiquei no último commit que eu fiz no meu repositório. Qualquer dúvida só falar que eu tento responder. Se você não conseguir resolver, não tem problema. Quinta eu vou pro laboratório e tento verificar

**Comment by fetim** [comment]
Lembra que a gente uma vez descobriu que a passagem de variáveis é meio confusa na f2py. A gente tinha que seguir algumas regras pra dar certo.

Acho que a gentr chegou a anotar isso em algum lugar, sabe onde foi?

**Comment by Caicau** [comment]
Então, eu me lembro que a gente teve dificuldade para passar matrizes e uma vez os valores iam trocados. A gente resolveu o primeiro gravando em arquivos pro Fortran ler e o segundo a gente resolveu pq descobrimos que nem todas as variáveis precisavam ser escritas, não sei explicar bem mas esse problema está descrito no arquivo "fortransubroutines.f90". Mas não lembro de termos problema em passar strings :(

**Comment by fetim** [comment]
Descobri o problema

no fortran existe um limite de caracteres por linha.
fiz uma quebra de linha da chamada da subroutina e funcionou.
