### ISSUE TITLE
Problema com o modelo homogeneo

### ISSUE THREAD

**Issue by Caicau** [GISIS-UFF/RTM_python-fortran#55]
@fetim Como te falei, o modelo homogêneo não está só com a camada de água  como esperado. Acredito que seja isto que esteja causando um sismograma com mais reflexões além da onda direta. 

Tentei colocar as imagens abaixo, não sei se vai funcionar

![modelo_homogeneo_com_problema](https://user-images.githubusercontent.com/34284723/42322788-21ace026-8034-11e8-94e5-f580164c6615.png)

![sismograma_homogeneo](https://user-images.githubusercontent.com/34284723/42322895-908ea696-8034-11e8-82fd-e35c3140f01b.png)

**Comment by fetim** [comment]
Funcionou perfeitamente. Consegui ver as imagens inclusive do email!!!

Bom... com certeza tem alguma coisa errada. Parece até que você usou outro modelo de velocidade para gerar esse sismograma! 

Assim que tiver um tempo dou uma olhada pra tentar achar o possivel erro

**Comment by Caicau** [comment]
Sim, exatamente! Eu comparei com o sismograma obtido usando o marmousi e eles me pareceram o mesmo. Não sei se em algum momento eu esqueci de mudar o modelo. Ainda assim o modelo homogêneo está errado. Temos que fazer outro, acho.

**Comment by fetim** [comment]
Consegui resolver. Tinha esquecido de passar o caminho do modelo para a função que faz a paralelização.

![image](https://user-images.githubusercontent.com/20346611/42395800-8d2084d2-8135-11e8-8563-a2547ff64189.png)

**Comment by Caicau** [comment]
Ebaa! Mas Felipe, o modelo tava errado tbm?

**Comment by fetim** [comment]
Não, usei o modelo que estava lá.
