### ISSUE TITLE
Verificação do script da matriz de tempo de trânsito

### ISSUE THREAD

**Issue by Caicau** [GISIS-UFF/RTM_python-fortran#57]
@fetim Felipe, o script rodou mas, eu to achando a matriz de tempo de trânsito com um artefato estranho na parte superior. Você pode dar uma olhada pra mim, por favor? Seguem abaixo as imagens da matriz e do modelo suavizado utilizado.

![ttm_marmousi_tiro_1_posicao_10](https://user-images.githubusercontent.com/34284723/42759303-eb208df8-88dc-11e8-826c-3d3ddc15229e.png)

![modelo_marmousi_suavizado](https://user-images.githubusercontent.com/34284723/42759417-4a12de88-88dd-11e8-82d3-79ca2a830fec.png)

**Comment by Caicau** [comment]
@fetim Eu já fiz o push para o meu diretório. Qualquer coisa você pde ver os códigos lá. :)

**Comment by fetim** [comment]
@Caicau, a gente precisa empilhar as imagem migradas para confirmar se esses artefatos afetam muito o resultado final. Faça teste, inicialmente com mais tiros (8 seria um bom numero para começar).

**Comment by Caicau** [comment]
@fetim  Tudo bem!
