### ISSUE TITLE
Implementar diferentes condições de imagens

### ISSUE THREAD

**Issue by fetim** [GISIS-UFF/RTM_python-fortran#59]
@Caicau 
definir quais condições iremos usar

**Comment by fetim** [comment]
@Caicau achei algumas referencias
[Max Wanlemberg Xavier Silva.PDF](https://github.com/GISIS-UFF/RTM_python-fortran/files/2259667/Max.Wanlemberg.Xavier.Silva.PDF)

[Silva_2009_Migração Reversa no Tempo com Diferentes Condições de Imagem.pdf](https://github.com/GISIS-UFF/RTM_python-fortran/files/2259674/Silva_2009_Migracao.Reversa.no.Tempo.com.Diferentes.Condicoes.de.Imagem.pdf)

**Comment by Caicau** [comment]
Nossaa! Que lindo! Muito obrigada Felipe! Vai me ajudar bastante :)

**Comment by fetim** [comment]
Vamos começar com a correlação cruzada.

Uma vez pronta, vai ser bem imediato testar a correlação cruzada normalizada.

**Comment by Caicau** [comment]
Sim, concordo! Acredito que agora podemos focar no laplaciano e assim que isso tiver finalizado, começamos essa condição
