### ISSUE TITLE
Aplicar o filtro Laplaciano na Imagem Final Migrada

### ISSUE THREAD

**Issue by Caicau** [GISIS-UFF/RTM_python-fortran#71]
Pensar em implementar isso para o artigo

**Comment by fetim** [comment]
@Caicau ,
Aqueles resultados e informações podem ser adicionadas nessa Issue. Pra gente acompanhar se tudo está funcionando corretamente

**Comment by Caicau** [comment]
Resultado 36 tiros

RTM Raw

![marmousi_36_tiros_raw](https://user-images.githubusercontent.com/34284723/53049377-b2608a00-3475-11e9-9201-9411d1c61b06.png)

RTM Laplaciano

![marmousi_36_tiros_laplaciano](https://user-images.githubusercontent.com/34284723/53049401-c1473c80-3475-11e9-91ef-e1eba4ab0b96.png)

*INFORMAÇÕES ADICIONAIS*

Modelo: Marmousi
Nx: 383
Nz: 141
Tempo T: 3 segundos

Teste 1:

Numero de tiros : 36
Posição inicial da Fonte: 10
Posição Final da Fonte: 360
Espaçamento: 10
Frequencia de Corte Sismogramas: 30Hz
Frequencia de Corte Matriz de Tempo de Transito:30Hz

Informações dos Processos

- Tempo de processamento:

Modelagem Sísmica: 174.8821988105774 segundos
Modelagem do Sismograma Homogêneo + Remoção da onda direta: 177.97777605056763 segundos
Matriz de Tempo de Trânsito: 174.75229907035828 segundos
Migração: 179.37088584899902 segundos
Stack: 7.9689788818359375 segundos
Laplaciano: 2.2644400596618652 segundos

Tempo Total de Processamento: 717.216578722 segundos 
Tempo Total de Processamento Aproximado: 12 minutos

**Comment by Caicau** [comment]
Resultado 48 Tiros TTM: 10Hz

RTM Raw

![marmousi_48_tiros_raw_ttm_10hz](https://user-images.githubusercontent.com/34284723/53050303-c86f4a00-3477-11e9-93ec-bbc096197b74.png)

RTM Laplaciano

![marmousi_48_tiros_laplaciano_ttm_10hz](https://user-images.githubusercontent.com/34284723/53050317-d0c78500-3477-11e9-9165-688171533981.png)


*INFORMAÇÕES ADICIONAIS*

Numero de tiros : 48
Posição inicial da Fonte: 8
Posição Final da Fonte: 384
Espaçamento: 8
Frequencia de Corte Sismogramas: 30Hz
Frequencia de Corte Matriz de Tempo de Transito: 12Hz

Informações dos Processos

Modelagem Sísmica: 193.62804794311523 segundos
Modelagem do Sismograma Homogêneo + Remoção da onda direta: 231.57901215553284 segundos
Matriz de Tempo de Trânsito: 238.46337985992432 segundos
Migração:235.51931619644165 segundos
Stack: 9.406560897827148 segundos
Laplaciano:  2.581709861755371 segundos

**Comment by Caicau** [comment]
Resultados: 48 tiros TTM: 25 Hz

RTM Raw

![marmousi_48_tiros_raw_ttm_25hz](https://user-images.githubusercontent.com/34284723/53051718-91029c80-347b-11e9-8b96-4ddaf89e2e22.png)

RTM Laplaciano

![marmousi_48_tiros_laplaciano_ttm_25hz](https://user-images.githubusercontent.com/34284723/53051730-9cee5e80-347b-11e9-9690-9a3b1d010e3a.png)

*INFORMAÇÕES ADICIONAIS*

Numero de tiros : 48
Posição inicial da Fonte: 8
Posição Final da Fonte: 384
Espaçamento: 8
Frequencia de Corte Sismogramas: 30Hz
Frequencia de Corte Matriz de Tempo de Transito: 25Hz

Informações dos Processos

Modelagem Sísmica: 208.32886004447937 segundos
Modelagem do Sismograma Homogêneo + Remoção da onda direta: 176.66257500648499 segundos
Matriz de Tempo de Trânsito: 149.59577107429504 segundos
Migração: 147.68521094322205 segundos
Stack: 3.9917430877685547 segundos
Laplaciano: 2.9807190895080566  segundos

**Comment by Caicau** [comment]
Resultados: 48 tiros TTM:20 Hz

RTM Raw
![marmousi_48_tiros_raw_ttm_20hz](https://user-images.githubusercontent.com/34284723/53052167-bba12500-347c-11e9-82ed-fb4c6d3db7ca.png)

RTM Laplaciano

![marmousi_48_tiros_laplaciano_ttm_20hz](https://user-images.githubusercontent.com/34284723/53052284-0d49af80-347d-11e9-95d8-887877a140a3.png)

*INFORMAÇÕES ADICIONAIS*

Teste 4:

Numero de tiros : 48
Posição inicial da Fonte: 8
Posição Final da Fonte: 384
Espaçamento: 8
Frequencia de Corte Sismogramas: 30Hz
Frequencia de Corte Matriz de Tempo de Transito: 20Hz

Informações dos Processos

Modelagem Sísmica: 208.32886004447937 segundos
Modelagem do Sismograma Homogêneo + Remoção da onda direta: 176.66257500648499 segundos
Matriz de Tempo de Trânsito: 144.3159499168396 segundos
Migração: 141.51269698143005 segundos
Stack: 3.316894054412842 segundos
Laplaciano: 2.7847859859466553  segundos

**Comment by Caicau** [comment]
-  Suavização : Fator 50

Marmousi Raw

![marmousi_model](https://user-images.githubusercontent.com/34284723/53128908-c32c0100-3544-11e9-9ddc-303efd377e5a.jpeg)

Marmousi Suavizado 

![marmousi_model_smothed_50](https://user-images.githubusercontent.com/34284723/53128920-d0e18680-3544-11e9-967d-f264611516e1.jpeg)

- Imagem Migrada: 48 tiros

RTM Raw
![marmousi_48_tiros_raw_ttm_20hz_suavizacao_50](https://user-images.githubusercontent.com/34284723/53130624-8e6e7880-3549-11e9-946f-5cf3cc197b04.png)

RTM Laplaciano
![marmousi_48_tiros_laplaciano_ttm_20hz_suavizacao_50](https://user-images.githubusercontent.com/34284723/53130642-97f7e080-3549-11e9-8bf3-095a2cb27402.png)

**Comment by fetim** [comment]
@Caicau, parece que aqueles artefatos que suspeitavamos ser da matrix tempo de transito realmente sumiram. Mas percebeu que houve uma mudança na amplitude? Ficaram bem mais fracas, não acha?
Outra coisa, aqueles artefatos verticais na região das falhas permaneceram, parece ser um problema da condição de image. 

Acho que vale a pena mais um teste com um modelo de velocidade intermediário para gente tirar essa dúvida. 

Não podemos esquecer de pontuar esse problema no artigo e no seu tcc (a necessidade de suaviazar o modelo de velocidade para aplicação da RTM por máx tempo de excitação)
:shipit:

**Comment by Caicau** [comment]
Teste: Mesmo modelo mas com a matriz de tempo de transito com a mesma frequencia do sismograma (30Hz)

Marmousi
![marmousi_model](https://user-images.githubusercontent.com/34284723/53367514-2a6efa00-3925-11e9-9d05-8376f95384b0.jpeg)

Marmousi Suavizado
![marmousi_model_smothed_50](https://user-images.githubusercontent.com/34284723/53367512-2a6efa00-3925-11e9-9c2a-add44b800756.jpeg)

RTM Raw
![marmousi_48_tiros_raw_ttm_30hz_suavizacao_50](https://user-images.githubusercontent.com/34284723/53367869-0364f800-3926-11e9-9eae-7a75d29ecbc4.png)

Laplaciano

![marmousi_48_tiros_laplaciano_ttm_30hz_suavizacao_50](https://user-images.githubusercontent.com/34284723/53367884-09f36f80-3926-11e9-8792-a69120965a07.png)


Não gostei do resultado mas acredito que o ruído já existia no outro teste. Minha teoria é que com a frequencia mais baixa não foi possível vizualizar esses ruídos.

**Comment by Caicau** [comment]
Usando frequencia 30Hz e suavizacao 30

RTM Raw
![marmousi_48_tiros_raw_ttm_30hz_suavizacao_30](https://user-images.githubusercontent.com/34284723/53371853-24324b00-3930-11e9-8d48-7a1ef8e9a23f.png)

Laplaciano

![marmousi_48_tiros_laplaciano_ttm_30hz_suavizacao_30](https://user-images.githubusercontent.com/34284723/53371864-2bf1ef80-3930-11e9-985f-767c870e1e2b.png)

**Comment by Caicau** [comment]
Suavização de 80 e frequencia de corte de 30Hz

Raw
![marmousi_48_tiros_raw_ttm_30hz_suavizacao_80](https://user-images.githubusercontent.com/34284723/53523771-6be5dd80-3abc-11e9-8aa2-317e39312c83.png)


Laplaciano
![marmousi_48_tiros_laplaciano_ttm_30hz_suavizacao_80](https://user-images.githubusercontent.com/34284723/53523777-6ee0ce00-3abc-11e9-9047-6c0e1e4c258b.png)

**Comment by Caicau** [comment]
60 tiros Suavização 50

Raw
![Marmousi_60_tiros_Raw_TTM_30Hz_Suavizacao_50](https://user-images.githubusercontent.com/34284723/54312332-71abea80-45b5-11e9-9e32-45d4c60bdd2e.png)

Laplaciano
![Marmousi_60_tiros_Laplaciano_TTM_30Hz_Suavizacao_50](https://user-images.githubusercontent.com/34284723/54312333-71abea80-45b5-11e9-8cf2-85646600e682.png)

**Comment by Caicau** [comment]
60 tiros Suavização 50

Laplaciano + Passa Banda

![Filtered_Marmousi_Laplaciano_Passa_Banda](https://user-images.githubusercontent.com/34284723/54314637-fb11eb80-45ba-11e9-8fee-20c2bc856ade.png)

**Comment by Caicau** [comment]
Marmousi

100 tiros, suavização 80 

Raw
![Marmousi_100_tiros_Raw_TTM_30Hz_Suavizacao_80](https://user-images.githubusercontent.com/34284723/54315760-d0756200-45bd-11e9-940c-1e37d0122ccb.png)

Laplaciano 
![Marmousi_100_tiros_Laplaciano_TTM_30Hz_Suavizacao_80](https://user-images.githubusercontent.com/34284723/54315770-d408e900-45bd-11e9-852c-ed342b48c50e.png)

Laplaciano + Passa Banda

![Filtered_Marmousi_Laplaciano_Passa_Banda_100tiros](https://user-images.githubusercontent.com/34284723/54316012-6c9f6900-45be-11e9-899f-def4a44d672a.png)

**Comment by Caicau** [comment]
Plano Paralelo

100 tiros, suavização 80 

Raw
![Plano_Paralelo_Raw_100_tiros_TTM_30Hz](https://user-images.githubusercontent.com/34284723/54319517-7e860980-45c8-11e9-9675-9e8e92eb4563.png)

Laplaciano 
![Plano_Paralelo_Laplaciano_100_tiros_TTM_30Hz](https://user-images.githubusercontent.com/34284723/54319523-8180fa00-45c8-11e9-8f32-e5d5f3bbd5cc.png)
