### ISSUE TITLE
Operador de modelagem

### ISSUE THREAD

**Issue by fetim** [GISIS-UFF/RTM_python-fortran#8]
Oi @Caicau. Mais tarefas :call_me_hand: 
- [x] Criar subrotina em fortran para realizar a modelagem e registrar os sismogramas.

- [x] Registrar os snapshots (opcional - o usuário decide)

- [x] Registrar matriz de tempo de trânsito

- [x] Começar a estudar a teoria de como é feita a condição de Imagem por correlação cruzada.

**Comment by Caicau** [comment]
Comparação dos tempos de execução do python e f2py (tempo do python = 77.302325964 segundos)

**Comment by fetim** [comment]
O modelo de velocidade para a condição de imagem é um modelo suavizado.
