### ISSUE TITLE
Verificar o Approach que será abordado no artigo (PRIORIDADE MAXIMA)

### ISSUE THREAD

**Issue by Caicau** [GISIS-UFF/RTM_python-fortran#81]
Conversar com o Felipe sobre isso

**Comment by fetim** [comment]
A gente pode começar com uma lista de tarefas como sempre.

Bom, acho que seria válido apresentarmos os resultados da migração RTM que temos aplicando o filtro Laplaciano. E confirmar se ele realmente melhora a imagem quando comparado ao filtro passa banda. E discutir se devemos aplicar os dois ou apenas um deles.

Pra começar:
* Gerar as imagens migradas sem filtro
* Gerar as imagens migradas com filtro passa banda
* Implementar o filtro Laplaciano
* Gerar as imagens migradas com filtro Laplaciano
* Gerar as imagens migradas com filtro passa-banda e Laplaciano

**Comment by Caicau** [comment]
Adoro uma lista de tarefas! Hahaha 
Gostei das tarefas que você disse! Creio que a gente consiga fazer isso. Eu tenho a imagem final do Marmousi e do plano paralelo sem filtros (Laplaciano e passa banda) prontos. Você sugere algum outro modelo?

**Comment by Caicau** [comment]
Adoro uma lista de tarefas! Hahaha 
Gostei das tarefas que você disse! Creio que a gente consiga fazer isso. Eu tenho a imagem final do Marmousi e do plano paralelo sem filtros (Laplaciano e passa banda) prontos. Você sugere algum outro modelo?
