### ISSUE TITLE
Atualizar o mute de longos offsets no codigo do Fortran 

### ISSUE THREAD

**Issue by Caicau** [GISIS-UFF/RTM_python-fortran#85]
Acrescentar uma soma suave

**Comment by Caicau** [comment]
mute:
![teste_taper](https://user-images.githubusercontent.com/34284723/56701361-210bcf00-66d5-11e9-8c61-a9d0d95e0376.png)

matriz antes do mute:
![matriz_bf_taper](https://user-images.githubusercontent.com/34284723/56701369-2b2dcd80-66d5-11e9-90c6-640cfdae45ce.png)

matriz depois do mute

![matriz_af_taper](https://user-images.githubusercontent.com/34284723/56701388-48629c00-66d5-11e9-928b-d4894fd04038.png)

Felipe, realizei o teste numa matriz aleatoria e ficou desse jeito. Por algum motivo a função que temos para ler binarios no python está com algum problema no reshape  e por isso não consegui testar na nossa imagem.

**Comment by Caicau** [comment]
taper de 200:
![taper_200](https://user-images.githubusercontent.com/34284723/56701639-83190400-66d6-11e9-8524-b009ea9f5346.png)

matriz antes 
![matriz_bf_taper](https://user-images.githubusercontent.com/34284723/56701633-7d232300-66d6-11e9-84d9-a1f2b29fb76a.png)
matriz depois

![matriz_af_taper_200](https://user-images.githubusercontent.com/34284723/56701635-7eece680-66d6-11e9-8fe7-e55789ea732a.png)

**Comment by fetim** [comment]
Muito bom @caicau!!!

Parece estar funcionando no primeiro caso.

Mas no segundo exemplo com um damping maior, eu esperava que abaixo 50 m e acima 550 m na direção x deveria estar zerado como no caso anterior.
